### PR TITLE
Add unit test code coverage

### PR DESCRIPTION
**Pull request by JohanLorenzo**

### CODE REVIEW

**Comment by Yoric** [comment]
Thanks for the pull request. Could you please move it to fxbox/adapters? :)

**Comment by JohanLorenzo** [comment]
Will do. I'm reopening this PR just to continue to fix Travis. I'll close it once it's done.

**Comment by JohanLorenzo** [comment]
Taxonomy was done in https://github.com/fxbox/taxonomy/pull/59 . Let's turn on code coverage here too. 

Like for taxonomy, let's wait until all the repos are ready before merging it. 

@fabricedesre I think we need to switch Coveralls on, here too.

r? @Yoric

**Comment by Yoric** [comment]
r=me, don't forget your FIXME

**Comment by Yoric** [comment]
r=me

**Comment by fabricedesre** [comment]
I updated to 04-10

**Comment by JohanLorenzo** [comment]
Re-using this PR to actually land code coverage

**Pull request merged**
